%% coding: utf-8
-file("/usr/local/lib/erlang/lib/parsetools-2.0.10/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(ice_scan).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("src/ice_scan.xrl", 160).

-file("/usr/local/lib/erlang/lib/parsetools-2.0.10/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transistion state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,_Tlen,_Ics1,L1,_S1} ->
            string_cont(yysuf(Tcs, Alen), L1, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->       % Use last accept match
            token_cont(yysuf(Tcs, Alen1), L1, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            tokens_cont(yysuf(Tcs, Alen1), L1, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            skip_cont(yysuf(Tcs, Alen1), L1, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("src/ice_scan.erl", 276).
yystate() -> 110.

yystate(144, [108|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 61, Tlen);
yystate(144, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(144, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(144, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(144, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(144, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(144, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,144};
yystate(143, [61|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 34, Tlen);
yystate(143, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line,143};
yystate(142, [59|Ics], Line, Tlen, Action, Alen) ->
    yystate(84, Ics, Line, Tlen+1, Action, Alen);
yystate(142, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,142};
yystate(141, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(141, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(141, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(141, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(141, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,141};
yystate(140, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line};
yystate(139, [111|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 61, Tlen);
yystate(139, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(139, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(139, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(139, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(139, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(139, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,139};
yystate(138, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(138, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(101, Ics, Line, Tlen+1, Action, Alen);
yystate(138, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(138, Ics, Line+1, Tlen+1, Action, Alen);
yystate(138, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(138, Ics, Line, Tlen+1, Action, Alen);
yystate(138, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(138, Ics, Line, Tlen+1, Action, Alen);
yystate(138, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(138, Ics, Line, Tlen+1, Action, Alen);
yystate(138, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(138, Ics, Line, Tlen+1, Action, Alen);
yystate(138, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,138};
yystate(137, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 10, Tlen);
yystate(137, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 10, Tlen);
yystate(137, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 10, Tlen);
yystate(137, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 10, Tlen);
yystate(137, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,137};
yystate(136, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(107, Ics, Line, Tlen+1, Action, Alen);
yystate(136, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,136};
yystate(135, [116|Ics], Line, Tlen, _, _) ->
    yystate(88, Ics, Line, Tlen+1, 61, Tlen);
yystate(135, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(135, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(135, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(135, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(135, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(135, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,135};
yystate(134, [96|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(134, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(134, Ics, Line+1, Tlen+1, Action, Alen);
yystate(134, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(134, Ics, Line, Tlen+1, Action, Alen);
yystate(134, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 95 ->
    yystate(134, Ics, Line, Tlen+1, Action, Alen);
yystate(134, [C|Ics], Line, Tlen, Action, Alen) when C >= 97 ->
    yystate(134, Ics, Line, Tlen+1, Action, Alen);
yystate(134, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,134};
yystate(133, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 20, Tlen);
yystate(133, [57|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 20, Tlen);
yystate(133, [56|Ics], Line, Tlen, _, _) ->
    yystate(66, Ics, Line, Tlen+1, 20, Tlen);
yystate(133, [52|Ics], Line, Tlen, _, _) ->
    yystate(66, Ics, Line, Tlen+1, 20, Tlen);
yystate(133, [51|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 20, Tlen);
yystate(133, [50|Ics], Line, Tlen, _, _) ->
    yystate(66, Ics, Line, Tlen+1, 20, Tlen);
yystate(133, [49|Ics], Line, Tlen, _, _) ->
    yystate(82, Ics, Line, Tlen+1, 20, Tlen);
yystate(133, [48|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 20, Tlen);
yystate(133, [C|Ics], Line, Tlen, _, _) when C >= 53, C =< 55 ->
    yystate(141, Ics, Line, Tlen+1, 20, Tlen);
yystate(133, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 20, Tlen);
yystate(133, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 20, Tlen);
yystate(133, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,133};
yystate(132, [114|Ics], Line, Tlen, _, _) ->
    yystate(1, Ics, Line, Tlen+1, 61, Tlen);
yystate(132, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(132, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(132, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(132, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(132, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(132, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,132};
yystate(131, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 28, Tlen);
yystate(131, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 28, Tlen);
yystate(131, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 28, Tlen);
yystate(131, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 28, Tlen);
yystate(131, Ics, Line, Tlen, _, _) ->
    {28,Tlen,Ics,Line,131};
yystate(130, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(130, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(138, Ics, Line+1, Tlen+1, Action, Alen);
yystate(130, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(138, Ics, Line, Tlen+1, Action, Alen);
yystate(130, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(138, Ics, Line, Tlen+1, Action, Alen);
yystate(130, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(138, Ics, Line, Tlen+1, Action, Alen);
yystate(130, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(138, Ics, Line, Tlen+1, Action, Alen);
yystate(130, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,130};
yystate(129, [114|Ics], Line, Tlen, _, _) ->
    yystate(133, Ics, Line, Tlen+1, 61, Tlen);
yystate(129, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(129, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(129, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(129, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(129, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(129, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,129};
yystate(128, [61|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line, Tlen+1, 23, Tlen);
yystate(128, Ics, Line, Tlen, _, _) ->
    {23,Tlen,Ics,Line,128};
yystate(127, [98|Ics], Line, Tlen, _, _) ->
    yystate(48, Ics, Line, Tlen+1, 61, Tlen);
yystate(127, [97|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(127, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(127, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(127, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(127, [C|Ics], Line, Tlen, _, _) when C >= 99, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(127, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,127};
yystate(126, [97|Ics], Line, Tlen, _, _) ->
    yystate(129, Ics, Line, Tlen+1, 61, Tlen);
yystate(126, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(126, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(126, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(126, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(126, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,126};
yystate(125, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line};
yystate(124, [37|Ics], Line, Tlen, _, _) ->
    yystate(89, Ics, Line, Tlen+1, 1, Tlen);
yystate(124, [10|Ics], Line, Tlen, _, _) ->
    yystate(124, Ics, Line+1, Tlen+1, 1, Tlen);
yystate(124, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(124, Ics, Line, Tlen+1, 1, Tlen);
yystate(124, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(124, Ics, Line, Tlen+1, 1, Tlen);
yystate(124, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,124};
yystate(123, [59|Ics], Line, Tlen, _, _) ->
    yystate(84, Ics, Line, Tlen+1, 57, Tlen);
yystate(123, Ics, Line, Tlen, _, _) ->
    {57,Tlen,Ics,Line,123};
yystate(122, [111|Ics], Line, Tlen, _, _) ->
    yystate(109, Ics, Line, Tlen+1, 61, Tlen);
yystate(122, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(122, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(122, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(122, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(122, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(122, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,122};
yystate(121, [47|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 40, Tlen);
yystate(121, Ics, Line, Tlen, _, _) ->
    {40,Tlen,Ics,Line,121};
yystate(120, Ics, Line, Tlen, _, _) ->
    {31,Tlen,Ics,Line};
yystate(119, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 4, Tlen);
yystate(119, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 4, Tlen);
yystate(119, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 4, Tlen);
yystate(119, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 4, Tlen);
yystate(119, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,119};
yystate(118, [97|Ics], Line, Tlen, _, _) ->
    yystate(105, Ics, Line, Tlen+1, 61, Tlen);
yystate(118, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(118, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(118, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(118, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(118, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,118};
yystate(117, Ics, Line, Tlen, _, _) ->
    {42,Tlen,Ics,Line};
yystate(116, [121|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(116, [122|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(116, [120|Ics], Line, Tlen, _, _) ->
    yystate(135, Ics, Line, Tlen+1, 61, Tlen);
yystate(116, [110|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 61, Tlen);
yystate(116, [109|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(116, [108|Ics], Line, Tlen, _, _) ->
    yystate(74, Ics, Line, Tlen+1, 61, Tlen);
yystate(116, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(116, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(116, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(116, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(116, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 119 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(116, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,116};
yystate(115, [111|Ics], Line, Tlen, _, _) ->
    yystate(112, Ics, Line, Tlen+1, 61, Tlen);
yystate(115, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(115, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(115, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(115, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(115, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(115, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,115};
yystate(114, [46|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 46, Tlen);
yystate(114, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(114, Ics, Line, Tlen+1, 46, Tlen);
yystate(114, Ics, Line, Tlen, _, _) ->
    {46,Tlen,Ics,Line,114};
yystate(113, [59|Ics], Line, Tlen, _, _) ->
    yystate(142, Ics, Line, Tlen+1, 0, Tlen);
yystate(113, [10|Ics], Line, Tlen, _, _) ->
    yystate(113, Ics, Line+1, Tlen+1, 0, Tlen);
yystate(113, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(113, Ics, Line, Tlen+1, 0, Tlen);
yystate(113, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(113, Ics, Line, Tlen+1, 0, Tlen);
yystate(113, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,113};
yystate(112, [97|Ics], Line, Tlen, _, _) ->
    yystate(1, Ics, Line, Tlen+1, 61, Tlen);
yystate(112, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(112, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(112, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(112, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(112, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,112};
yystate(111, [124|Ics], Line, Tlen, _, _) ->
    yystate(140, Ics, Line, Tlen+1, 51, Tlen);
yystate(111, Ics, Line, Tlen, _, _) ->
    {51,Tlen,Ics,Line,111};
yystate(110, [120756|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [120730|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [120698|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [120672|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [120640|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [120614|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [120582|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [120556|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [120524|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [120498|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [11415|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [11414|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [8595|Ics], Line, Tlen, Action, Alen) ->
    yystate(24, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [8594|Ics], Line, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [8593|Ics], Line, Tlen, Action, Alen) ->
    yystate(125, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [8592|Ics], Line, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [7463|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [955|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [923|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(64, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [124|Ics], Line, Tlen, Action, Alen) ->
    yystate(111, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [123|Ics], Line, Tlen, Action, Alen) ->
    yystate(73, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [119|Ics], Line, Tlen, Action, Alen) ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [118|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [117|Ics], Line, Tlen, Action, Alen) ->
    yystate(100, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(56, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [115|Ics], Line, Tlen, Action, Alen) ->
    yystate(65, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(141, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [113|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [112|Ics], Line, Tlen, Action, Alen) ->
    yystate(141, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(122, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [109|Ics], Line, Tlen, Action, Alen) ->
    yystate(141, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [108|Ics], Line, Tlen, Action, Alen) ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [106|Ics], Line, Tlen, Action, Alen) ->
    yystate(141, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [107|Ics], Line, Tlen, Action, Alen) ->
    yystate(141, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [105|Ics], Line, Tlen, Action, Alen) ->
    yystate(33, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [104|Ics], Line, Tlen, Action, Alen) ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [103|Ics], Line, Tlen, Action, Alen) ->
    yystate(141, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [102|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(116, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [100|Ics], Line, Tlen, Action, Alen) ->
    yystate(102, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [99|Ics], Line, Tlen, Action, Alen) ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [98|Ics], Line, Tlen, Action, Alen) ->
    yystate(68, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [97|Ics], Line, Tlen, Action, Alen) ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [96|Ics], Line, Tlen, Action, Alen) ->
    yystate(134, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(141, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [64|Ics], Line, Tlen, Action, Alen) ->
    yystate(108, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [62|Ics], Line, Tlen, Action, Alen) ->
    yystate(143, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(128, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [60|Ics], Line, Tlen, Action, Alen) ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [59|Ics], Line, Tlen, Action, Alen) ->
    yystate(123, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(121, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(104, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(83, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(4, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [41|Ics], Line, Tlen, Action, Alen) ->
    yystate(94, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [40|Ics], Line, Tlen, Action, Alen) ->
    yystate(97, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(62, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [38|Ics], Line, Tlen, Action, Alen) ->
    yystate(85, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(96, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(130, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(91, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(17, Ics, Line+1, Tlen+1, Action, Alen);
yystate(110, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(17, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 32 ->
    yystate(17, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [C|Ics], Line, Tlen, Action, Alen) when C >= 49, C =< 57 ->
    yystate(114, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, Action, Alen);
yystate(110, [C|Ics], Line, Tlen, Action, Alen) when C >= 120, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, Action, Alen);
yystate(110, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,110};
yystate(109, [116|Ics], Line, Tlen, _, _) ->
    yystate(53, Ics, Line, Tlen+1, 61, Tlen);
yystate(109, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(109, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(109, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(109, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(109, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(109, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,109};
yystate(108, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line};
yystate(107, Ics, Line, Tlen, _, _) ->
    {48,Tlen,Ics,Line};
yystate(106, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(79, Ics, Line, Tlen+1, Action, Alen);
yystate(106, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(79, Ics, Line, Tlen+1, Action, Alen);
yystate(106, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(106, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,106};
yystate(105, [100|Ics], Line, Tlen, _, _) ->
    yystate(133, Ics, Line, Tlen+1, 61, Tlen);
yystate(105, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(105, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(105, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(105, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(105, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(105, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,105};
yystate(104, Ics, Line, Tlen, _, _) ->
    {56,Tlen,Ics,Line};
yystate(103, [117|Ics], Line, Tlen, _, _) ->
    yystate(81, Ics, Line, Tlen+1, 61, Tlen);
yystate(103, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(103, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(103, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(103, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(103, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(103, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,103};
yystate(102, [111|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 61, Tlen);
yystate(102, [105|Ics], Line, Tlen, _, _) ->
    yystate(72, Ics, Line, Tlen+1, 61, Tlen);
yystate(102, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(102, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(102, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(102, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(102, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 110 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(102, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(102, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,102};
yystate(101, Ics, Line, Tlen, _, _) ->
    {50,Tlen,Ics,Line};
yystate(100, [115|Ics], Line, Tlen, _, _) ->
    yystate(65, Ics, Line, Tlen+1, 61, Tlen);
yystate(100, [108|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 61, Tlen);
yystate(100, [106|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(100, [107|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(100, [105|Ics], Line, Tlen, _, _) ->
    yystate(6, Ics, Line, Tlen+1, 61, Tlen);
yystate(100, [99|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 61, Tlen);
yystate(100, [97|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(100, [98|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(100, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(100, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(100, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(100, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 104 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(100, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 114 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(100, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(100, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,100};
yystate(99, [114|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 61, Tlen);
yystate(99, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(99, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(99, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(99, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(99, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(99, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,99};
yystate(98, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line};
yystate(97, Ics, Line, Tlen, _, _) ->
    {53,Tlen,Ics,Line};
yystate(96, [37|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line, Tlen+1, 41, Tlen);
yystate(96, Ics, Line, Tlen, _, _) ->
    {41,Tlen,Ics,Line,96};
yystate(95, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(95, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,95};
yystate(94, Ics, Line, Tlen, _, _) ->
    {60,Tlen,Ics,Line};
yystate(93, [97|Ics], Line, Tlen, _, _) ->
    yystate(144, Ics, Line, Tlen+1, 61, Tlen);
yystate(93, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(93, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(93, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(93, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(93, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,93};
yystate(92, [47|Ics], Line, Tlen, _, _) ->
    yystate(95, Ics, Line, Tlen+1, 2, Tlen);
yystate(92, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,92};
yystate(91, [61|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 26, Tlen);
yystate(91, Ics, Line, Tlen, _, _) ->
    {26,Tlen,Ics,Line,91};
yystate(90, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 12, Tlen);
yystate(90, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 12, Tlen);
yystate(90, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 12, Tlen);
yystate(90, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 12, Tlen);
yystate(90, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line,90};
yystate(89, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(89, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,89};
yystate(88, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 18, Tlen);
yystate(88, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 18, Tlen);
yystate(88, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 18, Tlen);
yystate(88, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 18, Tlen);
yystate(88, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,88};
yystate(87, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 6, Tlen);
yystate(87, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 6, Tlen);
yystate(87, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 6, Tlen);
yystate(87, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 6, Tlen);
yystate(87, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,87};
yystate(86, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 9, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 9, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 9, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 9, Tlen);
yystate(86, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,86};
yystate(85, [38|Ics], Line, Tlen, Action, Alen) ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(85, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,85};
yystate(84, [59|Ics], Line, Tlen, _, _) ->
    yystate(84, Ics, Line, Tlen+1, 0, Tlen);
yystate(84, [10|Ics], Line, Tlen, _, _) ->
    yystate(113, Ics, Line+1, Tlen+1, 0, Tlen);
yystate(84, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(113, Ics, Line, Tlen+1, 0, Tlen);
yystate(84, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(113, Ics, Line, Tlen+1, 0, Tlen);
yystate(84, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,84};
yystate(83, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line};
yystate(82, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(82, [54|Ics], Line, Tlen, _, _) ->
    yystate(66, Ics, Line, Tlen+1, 61, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 53 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 55, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(82, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,82};
yystate(81, [101|Ics], Line, Tlen, _, _) ->
    yystate(14, Ics, Line, Tlen+1, 61, Tlen);
yystate(81, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(81, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,81};
yystate(80, [100|Ics], Line, Tlen, _, _) ->
    yystate(131, Ics, Line, Tlen+1, 61, Tlen);
yystate(80, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(80, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,80};
yystate(79, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(79, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,79};
yystate(78, [110|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 61, Tlen);
yystate(78, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(78, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,78};
yystate(77, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 13, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 13, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 13, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 13, Tlen);
yystate(77, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line,77};
yystate(76, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 5, Tlen);
yystate(76, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 5, Tlen);
yystate(76, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 5, Tlen);
yystate(76, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 5, Tlen);
yystate(76, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,76};
yystate(75, [102|Ics], Line, Tlen, _, _) ->
    yystate(133, Ics, Line, Tlen+1, 61, Tlen);
yystate(75, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 101 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 103, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(75, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,75};
yystate(74, [115|Ics], Line, Tlen, _, _) ->
    yystate(0, Ics, Line, Tlen+1, 61, Tlen);
yystate(74, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(74, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,74};
yystate(73, Ics, Line, Tlen, _, _) ->
    {55,Tlen,Ics,Line};
yystate(72, [109|Ics], Line, Tlen, _, _) ->
    yystate(119, Ics, Line, Tlen+1, 61, Tlen);
yystate(72, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 108 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 110, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(72, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,72};
yystate(71, Ics, Line, Tlen, _, _) ->
    {24,Tlen,Ics,Line};
yystate(70, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(92, Ics, Line+1, Tlen+1, Action, Alen);
yystate(70, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,70};
yystate(69, [61|Ics], Line, Tlen, _, _) ->
    yystate(120, Ics, Line, Tlen+1, 30, Tlen);
yystate(69, [45|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 30, Tlen);
yystate(69, Ics, Line, Tlen, _, _) ->
    {30,Tlen,Ics,Line,69};
yystate(68, [111|Ics], Line, Tlen, _, _) ->
    yystate(139, Ics, Line, Tlen+1, 61, Tlen);
yystate(68, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(68, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,68};
yystate(67, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line};
yystate(66, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 20, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 20, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 20, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 20, Tlen);
yystate(66, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line,66};
yystate(65, [104|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 61, Tlen);
yystate(65, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 103 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 105, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(65, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,65};
yystate(64, Ics, Line, Tlen, _, _) ->
    {58,Tlen,Ics,Line};
yystate(63, [37|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [10|Ics], Line, Tlen, _, _) ->
    yystate(124, Ics, Line+1, Tlen+1, 1, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(124, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(124, Ics, Line, Tlen+1, 1, Tlen);
yystate(63, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,63};
yystate(62, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(62, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(136, Ics, Line+1, Tlen+1, Action, Alen);
yystate(62, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(136, Ics, Line, Tlen+1, Action, Alen);
yystate(62, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(136, Ics, Line, Tlen+1, Action, Alen);
yystate(62, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 91 ->
    yystate(136, Ics, Line, Tlen+1, Action, Alen);
yystate(62, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(136, Ics, Line, Tlen+1, Action, Alen);
yystate(62, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,62};
yystate(61, [111|Ics], Line, Tlen, _, _) ->
    yystate(19, Ics, Line, Tlen+1, 61, Tlen);
yystate(61, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(61, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,61};
yystate(60, [117|Ics], Line, Tlen, _, _) ->
    yystate(127, Ics, Line, Tlen+1, 61, Tlen);
yystate(60, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(60, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,60};
yystate(59, Ics, Line, Tlen, _, _) ->
    {44,Tlen,Ics,Line};
yystate(58, [46|Ics], Line, Tlen, _, _) ->
    yystate(117, Ics, Line, Tlen+1, 25, Tlen);
yystate(58, Ics, Line, Tlen, _, _) ->
    {25,Tlen,Ics,Line,58};
yystate(57, Ics, Line, Tlen, _, _) ->
    {59,Tlen,Ics,Line};
yystate(56, [114|Ics], Line, Tlen, _, _) ->
    yystate(103, Ics, Line, Tlen+1, 61, Tlen);
yystate(56, [104|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 61, Tlen);
yystate(56, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 103 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 105, C =< 113 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(56, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,56};
yystate(55, [103|Ics], Line, Tlen, _, _) ->
    yystate(133, Ics, Line, Tlen+1, 61, Tlen);
yystate(55, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 104, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(55, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,55};
yystate(54, [48|Ics], Line, Tlen, _, _) ->
    yystate(114, Ics, Line, Tlen+1, 46, Tlen);
yystate(54, [49|Ics], Line, Tlen, _, _) ->
    yystate(114, Ics, Line, Tlen+1, 46, Tlen);
yystate(54, [46|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 46, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 50, C =< 57 ->
    yystate(54, Ics, Line, Tlen+1, 46, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(44, Ics, Line, Tlen+1, 46, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(44, Ics, Line, Tlen+1, 46, Tlen);
yystate(54, Ics, Line, Tlen, _, _) ->
    {46,Tlen,Ics,Line,54};
yystate(53, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 38, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 38, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 38, Tlen);
yystate(53, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 38, Tlen);
yystate(53, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line,53};
yystate(52, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line};
yystate(51, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 7, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 7, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 7, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 7, Tlen);
yystate(51, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,51};
yystate(50, Ics, Line, Tlen, _, _) ->
    {21,Tlen,Ics,Line};
yystate(49, [101|Ics], Line, Tlen, _, _) ->
    yystate(78, Ics, Line, Tlen+1, 61, Tlen);
yystate(49, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(49, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,49};
yystate(48, [108|Ics], Line, Tlen, _, _) ->
    yystate(34, Ics, Line, Tlen+1, 61, Tlen);
yystate(48, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(48, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,48};
yystate(47, [102|Ics], Line, Tlen, _, _) ->
    yystate(86, Ics, Line, Tlen+1, 61, Tlen);
yystate(47, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 101 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 103, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(47, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,47};
yystate(46, [115|Ics], Line, Tlen, _, _) ->
    yystate(81, Ics, Line, Tlen+1, 61, Tlen);
yystate(46, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(46, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,46};
yystate(45, [102|Ics], Line, Tlen, Action, Alen) ->
    yystate(106, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(45, Ics, Line, Tlen+1, Action, Alen);
yystate(45, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,45};
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 50, C =< 57 ->
    yystate(44, Ics, Line, Tlen+1, 46, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(44, Ics, Line, Tlen+1, 46, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(44, Ics, Line, Tlen+1, 46, Tlen);
yystate(44, Ics, Line, Tlen, _, _) ->
    {46,Tlen,Ics,Line,44};
yystate(43, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 27, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 27, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 27, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 27, Tlen);
yystate(43, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line,43};
yystate(42, [97|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 61, Tlen);
yystate(42, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(42, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,42};
yystate(41, [110|Ics], Line, Tlen, _, _) ->
    yystate(76, Ics, Line, Tlen+1, 61, Tlen);
yystate(41, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(41, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,41};
yystate(40, [108|Ics], Line, Tlen, _, _) ->
    yystate(133, Ics, Line, Tlen+1, 61, Tlen);
yystate(40, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(40, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,40};
yystate(39, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 8, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 8, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 8, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 8, Tlen);
yystate(39, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line,39};
yystate(38, [104|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 61, Tlen);
yystate(38, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 103 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 105, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(38, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,38};
yystate(37, [100|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 61, Tlen);
yystate(37, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(37, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,37};
yystate(36, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(136, Ics, Line, Tlen+1, Action, Alen);
yystate(36, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(136, Ics, Line+1, Tlen+1, Action, Alen);
yystate(36, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(136, Ics, Line, Tlen+1, Action, Alen);
yystate(36, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 91 ->
    yystate(136, Ics, Line, Tlen+1, Action, Alen);
yystate(36, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(136, Ics, Line, Tlen+1, Action, Alen);
yystate(36, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,36};
yystate(35, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 11, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 11, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 11, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 11, Tlen);
yystate(35, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line,35};
yystate(34, [101|Ics], Line, Tlen, _, _) ->
    yystate(133, Ics, Line, Tlen+1, 61, Tlen);
yystate(34, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(34, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,34};
yystate(33, [110|Ics], Line, Tlen, _, _) ->
    yystate(1, Ics, Line, Tlen+1, 61, Tlen);
yystate(33, [102|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 61, Tlen);
yystate(33, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(33, [94|Ics], Line, Tlen, _, _) ->
    yystate(98, Ics, Line, Tlen+1, 61, Tlen);
yystate(33, [33|Ics], Line, Tlen, _, _) ->
    yystate(21, Ics, Line, Tlen+1, 61, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 101 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 103, C =< 109 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(33, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,33};
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(32, Ics, Line, Tlen+1, 47, Tlen);
yystate(32, Ics, Line, Tlen, _, _) ->
    {47,Tlen,Ics,Line,32};
yystate(31, [114|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 61, Tlen);
yystate(31, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(31, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,31};
yystate(30, [111|Ics], Line, Tlen, _, _) ->
    yystate(132, Ics, Line, Tlen+1, 61, Tlen);
yystate(30, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(30, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,30};
yystate(29, Ics, Line, Tlen, _, _) ->
    {28,Tlen,Ics,Line};
yystate(28, Ics, Line, Tlen, _, _) ->
    {49,Tlen,Ics,Line};
yystate(27, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line};
yystate(26, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line};
yystate(25, [117|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 61, Tlen);
yystate(25, [108|Ics], Line, Tlen, _, _) ->
    yystate(115, Ics, Line, Tlen+1, 61, Tlen);
yystate(25, [106|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(25, [107|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(25, [105|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 61, Tlen);
yystate(25, [97|Ics], Line, Tlen, _, _) ->
    yystate(7, Ics, Line, Tlen+1, 61, Tlen);
yystate(25, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 104 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 116 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(25, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,25};
yystate(24, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line};
yystate(23, [104|Ics], Line, Tlen, _, _) ->
    yystate(126, Ics, Line, Tlen+1, 61, Tlen);
yystate(23, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 103 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 105, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(23, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,23};
yystate(22, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(22, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(59, Ics, Line, Tlen+1, Action, Alen);
yystate(22, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,22};
yystate(21, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line};
yystate(20, [58|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 52, Tlen);
yystate(20, Ics, Line, Tlen, _, _) ->
    {52,Tlen,Ics,Line,20};
yystate(19, [110|Ics], Line, Tlen, _, _) ->
    yystate(55, Ics, Line, Tlen+1, 61, Tlen);
yystate(19, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(19, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,19};
yystate(18, Ics, Line, Tlen, _, _) ->
    {32,Tlen,Ics,Line};
yystate(17, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line};
yystate(16, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(16, [11|Ics], Line, Tlen, Action, Alen) ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(16, [12|Ics], Line, Tlen, Action, Alen) ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(16, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(92, Ics, Line+1, Tlen+1, Action, Alen);
yystate(16, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(16, [C|Ics], Line, Tlen, Action, Alen) when C >= 14 ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(16, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,16};
yystate(15, [117|Ics], Line, Tlen, _, _) ->
    yystate(118, Ics, Line, Tlen+1, 61, Tlen);
yystate(15, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(15, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,15};
yystate(14, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 45, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 45, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 45, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 45, Tlen);
yystate(14, Ics, Line, Tlen, _, _) ->
    {45,Tlen,Ics,Line,14};
yystate(13, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(138, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(138, Ics, Line+1, Tlen+1, Action, Alen);
yystate(13, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(138, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 91 ->
    yystate(138, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(138, Ics, Line, Tlen+1, Action, Alen);
yystate(13, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,13};
yystate(12, Ics, Line, Tlen, _, _) ->
    {43,Tlen,Ics,Line};
yystate(11, [101|Ics], Line, Tlen, _, _) ->
    yystate(90, Ics, Line, Tlen+1, 61, Tlen);
yystate(11, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(11, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,11};
yystate(10, [62|Ics], Line, Tlen, _, _) ->
    yystate(26, Ics, Line, Tlen+1, 37, Tlen);
yystate(10, Ics, Line, Tlen, _, _) ->
    {37,Tlen,Ics,Line,10};
yystate(9, Ics, Line, Tlen, _, _) ->
    {54,Tlen,Ics,Line};
yystate(8, [114|Ics], Line, Tlen, _, _) ->
    yystate(87, Ics, Line, Tlen+1, 61, Tlen);
yystate(8, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(8, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,8};
yystate(7, [108|Ics], Line, Tlen, _, _) ->
    yystate(46, Ics, Line, Tlen+1, 61, Tlen);
yystate(7, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(7, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,7};
yystate(6, [110|Ics], Line, Tlen, _, _) ->
    yystate(1, Ics, Line, Tlen+1, 61, Tlen);
yystate(6, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(6, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,6};
yystate(5, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(45, Ics, Line, Tlen+1, Action, Alen);
yystate(5, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,5};
yystate(4, Ics, Line, Tlen, _, _) ->
    {39,Tlen,Ics,Line};
yystate(3, [101|Ics], Line, Tlen, _, _) ->
    yystate(99, Ics, Line, Tlen+1, 61, Tlen);
yystate(3, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(3, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,3};
yystate(2, [110|Ics], Line, Tlen, _, _) ->
    yystate(80, Ics, Line, Tlen+1, 61, Tlen);
yystate(2, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(2, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,2};
yystate(1, [116|Ics], Line, Tlen, _, _) ->
    yystate(133, Ics, Line, Tlen+1, 61, Tlen);
yystate(1, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(1, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,1};
yystate(0, [105|Ics], Line, Tlen, _, _) ->
    yystate(47, Ics, Line, Tlen+1, 61, Tlen);
yystate(0, [101|Ics], Line, Tlen, _, _) ->
    yystate(137, Ics, Line, Tlen+1, 61, Tlen);
yystate(0, [95|Ics], Line, Tlen, _, _) ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 104 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(141, Ics, Line, Tlen+1, 61, Tlen);
yystate(0, Ics, Line, Tlen, _, _) ->
    {61,Tlen,Ics,Line,0};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, _, _, TokenLine) ->
    yyaction_0(TokenLine);
yyaction(1, _, _, TokenLine) ->
    yyaction_1(TokenLine);
yyaction(2, _, _, _) ->
    yyaction_2();
yyaction(3, _, _, _) ->
    yyaction_3();
yyaction(4, _, _, TokenLine) ->
    yyaction_4(TokenLine);
yyaction(5, _, _, TokenLine) ->
    yyaction_5(TokenLine);
yyaction(6, _, _, TokenLine) ->
    yyaction_6(TokenLine);
yyaction(7, _, _, TokenLine) ->
    yyaction_7(TokenLine);
yyaction(8, _, _, TokenLine) ->
    yyaction_8(TokenLine);
yyaction(9, _, _, TokenLine) ->
    yyaction_9(TokenLine);
yyaction(10, _, _, TokenLine) ->
    yyaction_10(TokenLine);
yyaction(11, _, _, TokenLine) ->
    yyaction_11(TokenLine);
yyaction(12, _, _, TokenLine) ->
    yyaction_12(TokenLine);
yyaction(13, _, _, TokenLine) ->
    yyaction_13(TokenLine);
yyaction(14, _, _, TokenLine) ->
    yyaction_14(TokenLine);
yyaction(15, _, _, TokenLine) ->
    yyaction_15(TokenLine);
yyaction(16, _, _, TokenLine) ->
    yyaction_16(TokenLine);
yyaction(17, _, _, TokenLine) ->
    yyaction_17(TokenLine);
yyaction(18, _, _, TokenLine) ->
    yyaction_18(TokenLine);
yyaction(19, _, _, TokenLine) ->
    yyaction_19(TokenLine);
yyaction(20, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_20(TokenChars, TokenLine);
yyaction(21, _, _, TokenLine) ->
    yyaction_21(TokenLine);
yyaction(22, _, _, TokenLine) ->
    yyaction_22(TokenLine);
yyaction(23, _, _, TokenLine) ->
    yyaction_23(TokenLine);
yyaction(24, _, _, TokenLine) ->
    yyaction_24(TokenLine);
yyaction(25, _, _, TokenLine) ->
    yyaction_25(TokenLine);
yyaction(26, _, _, TokenLine) ->
    yyaction_26(TokenLine);
yyaction(27, _, _, TokenLine) ->
    yyaction_27(TokenLine);
yyaction(28, _, _, TokenLine) ->
    yyaction_28(TokenLine);
yyaction(29, _, _, TokenLine) ->
    yyaction_29(TokenLine);
yyaction(30, _, _, TokenLine) ->
    yyaction_30(TokenLine);
yyaction(31, _, _, TokenLine) ->
    yyaction_31(TokenLine);
yyaction(32, _, _, TokenLine) ->
    yyaction_32(TokenLine);
yyaction(33, _, _, TokenLine) ->
    yyaction_33(TokenLine);
yyaction(34, _, _, TokenLine) ->
    yyaction_34(TokenLine);
yyaction(35, _, _, TokenLine) ->
    yyaction_35(TokenLine);
yyaction(36, _, _, TokenLine) ->
    yyaction_36(TokenLine);
yyaction(37, _, _, TokenLine) ->
    yyaction_37(TokenLine);
yyaction(38, _, _, TokenLine) ->
    yyaction_38(TokenLine);
yyaction(39, _, _, TokenLine) ->
    yyaction_39(TokenLine);
yyaction(40, _, _, TokenLine) ->
    yyaction_40(TokenLine);
yyaction(41, _, _, TokenLine) ->
    yyaction_41(TokenLine);
yyaction(42, _, _, TokenLine) ->
    yyaction_42(TokenLine);
yyaction(43, _, _, TokenLine) ->
    yyaction_43(TokenLine);
yyaction(44, _, _, TokenLine) ->
    yyaction_44(TokenLine);
yyaction(45, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_45(TokenChars, TokenLine);
yyaction(46, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_46(TokenChars, TokenLine);
yyaction(47, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_47(TokenChars, TokenLine);
yyaction(48, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_48(TokenChars, TokenLine);
yyaction(49, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_49(TokenChars, TokenLine);
yyaction(50, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_50(TokenChars, TokenLine);
yyaction(51, _, _, TokenLine) ->
    yyaction_51(TokenLine);
yyaction(52, _, _, TokenLine) ->
    yyaction_52(TokenLine);
yyaction(53, _, _, TokenLine) ->
    yyaction_53(TokenLine);
yyaction(54, _, _, TokenLine) ->
    yyaction_54(TokenLine);
yyaction(55, _, _, TokenLine) ->
    yyaction_55(TokenLine);
yyaction(56, _, _, TokenLine) ->
    yyaction_56(TokenLine);
yyaction(57, _, _, TokenLine) ->
    yyaction_57(TokenLine);
yyaction(58, _, _, TokenLine) ->
    yyaction_58(TokenLine);
yyaction(59, _, _, TokenLine) ->
    yyaction_59(TokenLine);
yyaction(60, _, _, TokenLine) ->
    yyaction_60(TokenLine);
yyaction(61, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_61(TokenChars, TokenLine);
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/1}).
-file("src/ice_scan.xrl", 87).
yyaction_0(TokenLine) ->
     { token, { ';;', TokenLine } } .

-compile({inline,yyaction_1/1}).
-file("src/ice_scan.xrl", 88).
yyaction_1(TokenLine) ->
     { token, { '%%', TokenLine } } .

-compile({inline,yyaction_2/0}).
-file("src/ice_scan.xrl", 89).
yyaction_2() ->
     skip_token .

-compile({inline,yyaction_3/0}).
-file("src/ice_scan.xrl", 90).
yyaction_3() ->
     skip_token .

-compile({inline,yyaction_4/1}).
-file("src/ice_scan.xrl", 92).
yyaction_4(TokenLine) ->
     { token, { dim, TokenLine } } .

-compile({inline,yyaction_5/1}).
-file("src/ice_scan.xrl", 93).
yyaction_5(TokenLine) ->
     { token, { 'fun', TokenLine } } .

-compile({inline,yyaction_6/1}).
-file("src/ice_scan.xrl", 94).
yyaction_6(TokenLine) ->
     { token, { var, TokenLine } } .

-compile({inline,yyaction_7/1}).
-file("src/ice_scan.xrl", 95).
yyaction_7(TokenLine) ->
     { token, { 'if', TokenLine } } .

-compile({inline,yyaction_8/1}).
-file("src/ice_scan.xrl", 96).
yyaction_8(TokenLine) ->
     { token, { then, TokenLine } } .

-compile({inline,yyaction_9/1}).
-file("src/ice_scan.xrl", 97).
yyaction_9(TokenLine) ->
     { token, { elsif, TokenLine } } .

-compile({inline,yyaction_10/1}).
-file("src/ice_scan.xrl", 98).
yyaction_10(TokenLine) ->
     { token, { else, TokenLine } } .

-compile({inline,yyaction_11/1}).
-file("src/ice_scan.xrl", 99).
yyaction_11(TokenLine) ->
     { token, { fi, TokenLine } } .

-compile({inline,yyaction_12/1}).
-file("src/ice_scan.xrl", 100).
yyaction_12(TokenLine) ->
     { token, { where, TokenLine } } .

-compile({inline,yyaction_13/1}).
-file("src/ice_scan.xrl", 101).
yyaction_13(TokenLine) ->
     { token, { 'end', TokenLine } } .

-compile({inline,yyaction_14/1}).
-file("src/ice_scan.xrl", 103).
yyaction_14(TokenLine) ->
     { token, { '^|', TokenLine } } .

-compile({inline,yyaction_15/1}).
-file("src/ice_scan.xrl", 104).
yyaction_15(TokenLine) ->
     { token, { '^|', TokenLine } } .

-compile({inline,yyaction_16/1}).
-file("src/ice_scan.xrl", 105).
yyaction_16(TokenLine) ->
     { token, { 'v|', TokenLine } } .

-compile({inline,yyaction_17/1}).
-file("src/ice_scan.xrl", 106).
yyaction_17(TokenLine) ->
     { token, { 'v|', TokenLine } } .

-compile({inline,yyaction_18/1}).
-file("src/ice_scan.xrl", 107).
yyaction_18(TokenLine) ->
     { token, { ext, TokenLine } } .

-compile({inline,yyaction_19/1}).
-file("src/ice_scan.xrl", 108).
yyaction_19(TokenLine) ->
     { token, { '::', TokenLine } } .

-compile({inline,yyaction_20/2}).
-file("src/ice_scan.xrl", 109).
yyaction_20(TokenChars, TokenLine) ->
     { token, { cl_scalar, TokenLine, TokenChars } } .

-compile({inline,yyaction_21/1}).
-file("src/ice_scan.xrl", 111).
yyaction_21(TokenLine) ->
     { token, { '<-', TokenLine } } .

-compile({inline,yyaction_22/1}).
-file("src/ice_scan.xrl", 112).
yyaction_22(TokenLine) ->
     { token, { '->', TokenLine } } .

-compile({inline,yyaction_23/1}).
-file("src/ice_scan.xrl", 113).
yyaction_23(TokenLine) ->
     { token, { '=', TokenLine } } .

-compile({inline,yyaction_24/1}).
-file("src/ice_scan.xrl", 114).
yyaction_24(TokenLine) ->
     { token, { '\\', TokenLine } } .

-compile({inline,yyaction_25/1}).
-file("src/ice_scan.xrl", 116).
yyaction_25(TokenLine) ->
     { token, { '.', TokenLine } } .

-compile({inline,yyaction_26/1}).
-file("src/ice_scan.xrl", 117).
yyaction_26(TokenLine) ->
     { token, { '!', TokenLine } } .

-compile({inline,yyaction_27/1}).
-file("src/ice_scan.xrl", 118).
yyaction_27(TokenLine) ->
     { token, { 'or', TokenLine } } .

-compile({inline,yyaction_28/1}).
-file("src/ice_scan.xrl", 119).
yyaction_28(TokenLine) ->
     { token, { 'and', TokenLine } } .

-compile({inline,yyaction_29/1}).
-file("src/ice_scan.xrl", 120).
yyaction_29(TokenLine) ->
     { token, { '@', TokenLine } } .

-compile({inline,yyaction_30/1}).
-file("src/ice_scan.xrl", 121).
yyaction_30(TokenLine) ->
     { token, { '<', TokenLine } } .

-compile({inline,yyaction_31/1}).
-file("src/ice_scan.xrl", 122).
yyaction_31(TokenLine) ->
     { token, { '<=', TokenLine } } .

-compile({inline,yyaction_32/1}).
-file("src/ice_scan.xrl", 123).
yyaction_32(TokenLine) ->
     { token, { '==', TokenLine } } .

-compile({inline,yyaction_33/1}).
-file("src/ice_scan.xrl", 124).
yyaction_33(TokenLine) ->
     { token, { '>=', TokenLine } } .

-compile({inline,yyaction_34/1}).
-file("src/ice_scan.xrl", 125).
yyaction_34(TokenLine) ->
     { token, { '>', TokenLine } } .

-compile({inline,yyaction_35/1}).
-file("src/ice_scan.xrl", 126).
yyaction_35(TokenLine) ->
     { token, { '!=', TokenLine } } .

-compile({inline,yyaction_36/1}).
-file("src/ice_scan.xrl", 127).
yyaction_36(TokenLine) ->
     { token, { '+', TokenLine } } .

-compile({inline,yyaction_37/1}).
-file("src/ice_scan.xrl", 128).
yyaction_37(TokenLine) ->
     { token, { '-', TokenLine } } .

-compile({inline,yyaction_38/1}).
-file("src/ice_scan.xrl", 129).
yyaction_38(TokenLine) ->
     { token, { 'not', TokenLine } } .

-compile({inline,yyaction_39/1}).
-file("src/ice_scan.xrl", 130).
yyaction_39(TokenLine) ->
     { token, { '*', TokenLine } } .

-compile({inline,yyaction_40/1}).
-file("src/ice_scan.xrl", 131).
yyaction_40(TokenLine) ->
     { token, { '/', TokenLine } } .

-compile({inline,yyaction_41/1}).
-file("src/ice_scan.xrl", 132).
yyaction_41(TokenLine) ->
     { token, { '%', TokenLine } } .

-compile({inline,yyaction_42/1}).
-file("src/ice_scan.xrl", 133).
yyaction_42(TokenLine) ->
     { token, { '..', TokenLine } } .

-compile({inline,yyaction_43/1}).
-file("src/ice_scan.xrl", 134).
yyaction_43(TokenLine) ->
     { token, { '#.', TokenLine } } .

-compile({inline,yyaction_44/1}).
-file("src/ice_scan.xrl", 135).
yyaction_44(TokenLine) ->
     { token, { '#!', TokenLine } } .

-compile({inline,yyaction_45/2}).
-file("src/ice_scan.xrl", 137).
yyaction_45(TokenChars, TokenLine) ->
     { token, { bool, TokenLine, TokenChars } } .

-compile({inline,yyaction_46/2}).
-file("src/ice_scan.xrl", 138).
yyaction_46(TokenChars, TokenLine) ->
     { token, { int, TokenLine, TokenChars } } .

-compile({inline,yyaction_47/2}).
-file("src/ice_scan.xrl", 139).
yyaction_47(TokenChars, TokenLine) ->
     { token, { float, TokenLine, TokenChars } } .

-compile({inline,yyaction_48/2}).
-file("src/ice_scan.xrl", 140).
yyaction_48(TokenChars, TokenLine) ->
     { token, { char, TokenLine, TokenChars } } .

-compile({inline,yyaction_49/2}).
-file("src/ice_scan.xrl", 141).
yyaction_49(TokenChars, TokenLine) ->
     { token, { raw_string, TokenLine, TokenChars } } .

-compile({inline,yyaction_50/2}).
-file("src/ice_scan.xrl", 142).
yyaction_50(TokenChars, TokenLine) ->
     { token, { cooked_string, TokenLine, TokenChars } } .

-compile({inline,yyaction_51/1}).
-file("src/ice_scan.xrl", 144).
yyaction_51(TokenLine) ->
     { token, { '|', TokenLine } } .

-compile({inline,yyaction_52/1}).
-file("src/ice_scan.xrl", 145).
yyaction_52(TokenLine) ->
     { token, { ':', TokenLine } } .

-compile({inline,yyaction_53/1}).
-file("src/ice_scan.xrl", 146).
yyaction_53(TokenLine) ->
     { token, { '(', TokenLine } } .

-compile({inline,yyaction_54/1}).
-file("src/ice_scan.xrl", 147).
yyaction_54(TokenLine) ->
     { token, { '[', TokenLine } } .

-compile({inline,yyaction_55/1}).
-file("src/ice_scan.xrl", 148).
yyaction_55(TokenLine) ->
     { token, { '{', TokenLine } } .

-compile({inline,yyaction_56/1}).
-file("src/ice_scan.xrl", 149).
yyaction_56(TokenLine) ->
     { token, { ',', TokenLine } } .

-compile({inline,yyaction_57/1}).
-file("src/ice_scan.xrl", 150).
yyaction_57(TokenLine) ->
     { token, { ';', TokenLine } } .

-compile({inline,yyaction_58/1}).
-file("src/ice_scan.xrl", 151).
yyaction_58(TokenLine) ->
     { token, { '}', TokenLine } } .

-compile({inline,yyaction_59/1}).
-file("src/ice_scan.xrl", 152).
yyaction_59(TokenLine) ->
     { token, { ']', TokenLine } } .

-compile({inline,yyaction_60/1}).
-file("src/ice_scan.xrl", 153).
yyaction_60(TokenLine) ->
     { token, { ')', TokenLine } } .

-compile({inline,yyaction_61/2}).
-file("src/ice_scan.xrl", 156).
yyaction_61(TokenChars, TokenLine) ->
     { token, { id, TokenLine, TokenChars } } .

-file("/usr/local/lib/erlang/lib/parsetools-2.0.10/include/leexinc.hrl", 282).
